### ISSUE TITLE
OSX: sed -r isn't available

### ISSUE THREAD

**Issue by rstacruz** [thebearjew/commit-comments#2]
The post-commit hook gets me this:

```
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Comment by rstacruz** [comment]
...Well, yes, it seems only GNU sed is supported. For us peasants on OSX, use Homebrew to install GNU sed like so:

```
brew reinstall gnu-sed --with-default-names
```

**Comment by rstacruz** [comment]
okay, but there's still a problem with grep:

```
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]
```

**Comment by jryio** [comment]
I made a quick Pull Request to remove a stray GNU grep style command from the `post-commit` hook. Thanks for bringing this to my attention.

Test out the PR branch if you could and let me know if you run into any more POSIX/GNU issues!
