### ISSUE TITLE
pcregrep not found in post-commit

### ISSUE THREAD

**Issue by fbartels** [thebearjew/commit-comments#6]
Hi Jacob,

I just tried your scripts and wanted to let you know that you get the following error message in case you do not have pcregrep installed (on commit obviously):

`.git/hooks/post-commit: line 15: pcregrep: command not found`

Maybe I'll make a pull request with a patch later, but wanted to anyway already document to error.

Regards

**Comment by jryio** [comment]
Thank you very much!

Would you mind letting me know which Operating System you're running and which version as well. Also Bash version would be very helpful too.

**Comment by fbartels** [comment]
Sure, I've observed this on Ubuntu 14.04, bash is "GNU bash, Version 4.3.11(1)-release (x86_64-pc-linux-gnu)"

**Comment by jryio** [comment]
I will add a similar conditional to the `post-commit` hook as is in the `prepare-commit-msg` hook to check if pcregrep is present. I apologize for leaving out the portability check.

Additionally, I did look up [all packages which ship with Ubuntu 14.04](http://releases.ubuntu.com/14.04/ubuntu-14.04.3-desktop-amd64.manifest) - and pcregrep is not included. I apologize for the oversight. Fix coming immediately.

**Comment by jryio** [comment]
If you could checkout PR #7 and verify that GNU grep is being used in the post-commit hook that would be much appreciated!

:rocket:

**Comment by fbartels** [comment]
Hi, thanks for the fast fix. I've checked out your branch and do not see the error message anymore.

Yes, I have seen that the package is also available on Ubuntu, but then I would have to install everywhere. Centrally managed hooks are quite easy, synced packages lists not much so ;-).

**Comment by jryio** [comment]
:tada:
