### ISSUE TITLE
Overzealous commits when using `git add --patch`

### ISSUE THREAD

**Issue by bogwonch** [thebearjew/commit-comments#9]
When using `git add --patch` commit-comments from outside the current patch are added to the commit message and all commit tags are removed, not just those from the current patch.

For example, say I have the following diff of a file in my repo:

```
 #! /usr/bin/env python

+#@commit greeting alice
+print("Hi Alice")
+
 print("Hello World")
+
+#@commit say goodbye
+print("Goodbye World")
```

I add the first hunk using `git add --patch`, but ignore the second hunk.
The commit message I get is:

```
 - [test.py#3] greeting alice
 - [test.py#8] say goodbye
```

And after removing the commit-comments the file looks like:

```
#! /usr/bin/env python

print("Hi Alice")

print("Hello World")

print("Goodbye World")
```

The correct behaviour should be for the commit message to be:

```
 - [test.py#3] greeting alice
```

And the file to be:

```
#! /usr/bin/env python

print("Hi Alice")

print("Hello World")

#@commit say goodbye
print("Goodbye World")
```

(Loving the tool by-the-way!)

**Comment by ghost** [comment]
Can see you're working on it as part of issue #1.
Apologies for the noise.

**Comment by jryio** [comment]
No this is not noise at all! 

I will make a pull request for this right away. Having not heavily used `git add --patch` myself, I appreciate the detail and correct output you provided.

The overarching plan was to use `git diff --cached --name-status --diff-filter=ACM` to only inspect Added, Created, or Modified files. However, that doesn't resolve the `--patch` issue.

**Comment by FranDias** [comment]
🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🍶 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕 🖕

**Comment by FranDias** [comment]
ps. suck it bog
